### DISCUSSION TITLE
configurer and vault in different kubernetes clusters

### DISCUSSION THREAD

**Discussion by johnny990** [bank-vaults/vault-operator#216] [Q&A] [answered]
Hi,
is it possible to deploy vault configurer and vault itself in different clusters? Or is it possible to disable configurer somehow?

I have the following security critical use case:
- there is `unsealing vault` which deployed on separate machine highly secured (access restricted only to several trusted persons)
- there are multiple tenant vaults where we have configured autounseal via `unsealing vault`. These tenants less secured, but we'd like to secure vault itself as much as possible (no root tokens in secrets on these tenants, central vault token should allow only autounseal). The ratio is that if somebody get access to tenant vault namespace it will be difficult to get access to tenant vault's secrets without its root token.

But this scenario is almost not possible because we have configurer which require root token to configure roles, policies, etc on tenant vaults. If we remove root token, it complains and can't access vault.

So, the idea is to configure tenant vaults externally either by configurer deployed remotely (if it's possible) or via custom external scripts.

Does it make sense? Or it's overengineering without real security benefits?

**Comment by akijakya** [comment]
Hi @johnny990, thank you for using Bank-Vaults!

Do I understand correctly that the problem here is that the configurer stores the root and unseal tokens in a Kubernetes secret? As per the [docs](https://bank-vaults.dev/docs/cli-tool/) this option is only for development purposes, these tokens should be stored in a more secure environment indeed. In `vault-operator`, the location of the tokens can be configured in the crd under `spec.unsealConfig`, you can find some examples [here](https://github.com/bank-vaults/vault-operator/tree/main/deploy/examples)!

**Reply by johnny990** [reply]
Hi @akijakya , thanks for a prompt reply!
actually I store root and other tokens in `unsealing vault`, but that doesn't help much, since if the intruder gets access to the tenant cluster he will be able to access secret where I store `VAULT_TOKEN` to access anything in `spec.unsealConfig`. That's why I'd like to leave on tenant cluster only `autounseal` token and move configurer part out of it.

So, here's my configuration if it will help.
`tenant vault`:
``` 
unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
    vault:
      address: "{{ .Values.unsealingVaultHost }}"
      unsealKeysPath: secret/data/vault/{{ .Release.Namespace }}/vault-keys

vaultEnvsConfig:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-central-token
        key: VAULT_TOKEN
  - name: VAULT_SKIP_VERIFY
    value: "true"

envsConfig:
  - name: VAULT_SKIP_VERIFY
    value: "true"
 - name: VAULT_TOKEN
   valueFrom:
     secretKeyRef:
      name: vault-central-token
       key: VAULT_TOKEN
```

policy in `unsealing vault`:

``` policies:
      {{ range .Values.tenants }}
      - name: allow_{{ . }}_transit
        rules: path "{{ . }}/transit/encrypt/autounseal" {
                 capabilities = ["update"]
                }
               path "{{ . }}/transit/decrypt/autounseal" {
                 capabilities = ["update"]
               }
               path "secret/data/vault/{{ . }}/*" {
                 capabilities = ["create", "read", "update", "delete", "list"]
               }
      {{ end }}
```

Let me know if you need additional information about my setup.

So, reducing to a short statement: to configure tenant vault I need root token, but if I put this root token somewhere where configurer is deployed (or if I put it in another vault but provide configurer with permissions to get it) means that somebody else could get it. 
The only way to avoid this I see the option to separate tenant vault and its configurer to different clusters. Does it make sense?
