### ISSUE TITLE
Operator panics when no storage is set

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/vault-operator#189]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.21.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.27.4

### Kubernetes Distribution/Provisioner

kind

### Expected Behavior

When passing invalid configuration to the Vault CR the operator should either reject it or ignore/log the fact that it cannot create the Vault instance (probably also set a status/event on the CR).

### Actual Behavior

The operator panics and gets into a crash loop.

### Configuration

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 1

  image: hashicorp/vault:1.14.1

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    ui: true
    log_level: debug

  # See: https://bank-vaults.dev/docs/cli-tool/#example-external-vault-configuration
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    auth:
      - type: kubernetes
        roles:
          # Default role assumed by workloads by default
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["*"]
            bound_service_account_namespaces: ["default"]
            policies: ["allow_secrets"]
            ttl: 1h

          # Allow access for the vault secrets webhook
          # Necessary to mutate secrets and configmaps
          # Add 'vault.security.banzaicloud.io/vault-role: "vault-secrets-webhook"' annotation to resources to use this role
          - name: vault-secrets-webhook
            bound_service_account_names: ["vault-secrets-webhook"]
            bound_service_account_namespaces: ["vault-system"]
            policies: ["allow_secrets"]
            ttl: 1h

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t
      - type: kv
        path: secret/data/dockerrepo
        data:
          data:
            DOCKER_REPO_USER: dockerrepouser
            DOCKER_REPO_PASSWORD: dockerrepopassword
      - type: kv
        path: secret/data/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD: s3cr3t
            MYSQL_PASSWORD: 3xtr3ms3cr3t
```

### Logs

```shell
{"level":"info","ts":"2023-09-06T10:51:18Z","msg":"Observed a panic in reconciler: runtime error: index out of range [0] with length 0","controller":"vault-controller","object":{"n
ame":"vault","namespace":"default"},"namespace":"default","name":"vault","reconcileID":"a4325df2-2359-40ed-8999-79054f8181c4"}
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 63 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1a4
panic({0x157c060, 0x4000960528})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/bank-vaults/vault-operator/pkg/apis/vault/v1alpha1.(*VaultSpec).GetStorageType(0x4000aa0108?)
        /usr/local/src/vault-operator/pkg/apis/vault/v1alpha1/vault_types.go:365 +0x118
github.com/bank-vaults/vault-operator/pkg/apis/vault/v1alpha1.(*VaultSpec).IsRaftStorage(...)
        /usr/local/src/vault-operator/pkg/apis/vault/v1alpha1/vault_types.go:613
github.com/bank-vaults/vault-operator/pkg/controller/vault.statefulSetForVault(0x4000aa0000, {0x400096d6c0, 0x0, 0x0}, 0x1b3bb18?, 0x4000101b80?)
        /usr/local/src/vault-operator/pkg/controller/vault/vault_controller.go:1159 +0xa38
github.com/bank-vaults/vault-operator/pkg/controller/vault.(*ReconcileVault).Reconcile(0x40006502d0, {0x1b26de8, 0x400054ec90}, {{{0x4000a019c5?, 0x400054ec90?}, {0x4000a019c0?, 0x
ffff700b1a01?}}})
        /usr/local/src/vault-operator/pkg/controller/vault/vault_controller.go:450 +0x1794
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b26de8?, {0x1b26de8?, 0x400054ec90?}, {{{0x4000a019c5?, 0x13b95a0?}, {0x4000a019c0?, 0x400096de08?
}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x4000621220, {0x1b26d40, 0x400026f1d0}, {0x14e0e20?, 0x40005561e0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x2cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x4000621220, {0x1b26d40, 0x400026f1d0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1a0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x43c
```
