### ISSUE TITLE
Override resources for vault sidecars

### ISSUE THREAD

**Issue by cjyar** [bank-vaults/vault-operator#213]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

I'd like to override the `resources.requests` fields of Vault's sidecar containers, but it doesn't appear to be possible.

### Proposed Solution

It would be great if I could use `spec.vaultPodSpec.containers` the same way I'd use a strategic merge patch with kubectl:
```yaml
spec:
  vaultPodSpec:
    containers:
    - name: bank-vaults
      resources:
        requests:
          cpu: 10m
```

Mergo doesn't seem to support that. If I try it now, it replaces `containers` instead of merging into it. I think [kyaml](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml) is what does this strategic merge logic for kustomize. If that worked, it would provide a generalized solution.

### Alternatives Considered

It would also work to add CRD fields like `bankVaultsSidecarResources` and `prometheusSidecarResources`.
