### ISSUE TITLE
Secrets are not mounted in main container, when using vault-agent-init

### ISSUE THREAD

**Issue by sando38** [bank-vaults/vault-operator#249]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.21.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.27.2

### Kubernetes Distribution/Provisioner

Scaleway

### Expected Behavior

The main container has secrets available at e.g. `/vault/secrets`

### Actual Behavior

No `volumeMount` for `/vault/secrets` is available in the main containers (my application, see config example below).

### Steps To Reproduce

This does not work:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpush-config-apns-vault-agent
  namespace: fpush
  labels:
    app.kubernetes.io/name: fpush
    my-app.kubernetes.io/name: fpush
data:
  config.hcl: |
    vault {
    }
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "fpush"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    template {
    contents = <<EOH
    {{- with secret "/secret/applications/production/fpush_apns" -}}
    {{ base64Decode .Data.data.certFile }}
    {{- end }}
    EOH
      destination = "/vault/secrets/apns_certificates.p12"
      exec {
        command = ["true"]
      }
    }
    template {
    contents = <<EOH
    {{- with secret "/secret/applications/production/ejabberd_listener_fpush" }}
    {
    "component": {
        "componentHostname": "fpush-apns.example.net",
        "componentKey": "{{ .Data.data.password_apns }}",
        "serverHostname": "ejabberd.ejabberd.svc.cluster.local",
        "serverPort": 5347
    },
    {{ end }}
    {{- with secret "/secret/applications/production/fpush_apns" }}
    "pushModules": {
        "iOS": {
            "type": "apple",
            "is_default_module": true,
            "apns": {
                "certFilePath": "/vault/secrets/apns_certificates.p12",
                "certPassword": "{{ .Data.data.certPassword }}",
                "environment": "{{ .Data.data.environment }}",
                "topic": "{{ .Data.data.topic }}"
            },
            "ratelimit": {
                "ratelimitTime": "20s",
                "hardRatelimitTime": "20s",
                "ratelimitCleanupInterval": "300s",
                "enabled": false
            }
        }
    },
    "timeout": {
        "xmppconnectionError": "20s"
    }
    }
    {{ end }}
    EOH
      destination = "/vault/secrets/settings.json"
      exec {
        command = ["true "]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: fpush
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        sidecar.istio.io/inject: "true"
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "fpush"
        vault.security.banzaicloud.io/vault-skip-verify: "false"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-agent: "true"
        vault.security.banzaicloud.io/vault-agent-init: "true"
        vault.security.banzaicloud.io/vault-agent-configmap: "fpush-config-apns-vault-agent"
        vault.security.banzaicloud.io/vault-agent-once: "true"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: default
      containers:
      - name: busybox
        image: busybox
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65532
          runAsGroup: 1000
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop: [ALL]
        args: ["/bin/sh", "-c", "sleep 120"]
```

However, when I trick the environment by also using vault-env to inject a pseudo environment variable, a `volumeMount` `/vault` is created which makes the secrets available from the vault-agent init container.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpush-config-apns-vault-agent
  namespace: fpush
  labels:
    app.kubernetes.io/name: fpush
    my-app.kubernetes.io/name: fpush
data:
  config.hcl: |
    vault {
    }
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "fpush"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    template {
    contents = <<EOH
    {{- with secret "/secret/applications/production/fpush_apns" -}}
    {{ base64Decode .Data.data.certFile }}
    {{- end }}
    EOH
      destination = "/vault/secrets/apns_certificates.p12"
      exec {
        command = ["true"]
      }
    }
    template {
    contents = <<EOH
    {{- with secret "/secret/applications/production/ejabberd_listener_fpush" }}
    {
    "component": {
        "componentHostname": "fpush-apns.example.net",
        "componentKey": "{{ .Data.data.password_apns }}",
        "serverHostname": "ejabberd.ejabberd.svc.cluster.local",
        "serverPort": 5347
    },
    {{ end }}
    {{- with secret "/secret/applications/production/fpush_apns" }}
    "pushModules": {
        "iOS": {
            "type": "apple",
            "is_default_module": true,
            "apns": {
                "certFilePath": "/vault/secrets/apns_certificates.p12",
                "certPassword": "{{ .Data.data.certPassword }}",
                "environment": "{{ .Data.data.environment }}",
                "topic": "{{ .Data.data.topic }}"
            },
            "ratelimit": {
                "ratelimitTime": "20s",
                "hardRatelimitTime": "20s",
                "ratelimitCleanupInterval": "300s",
                "enabled": false
            }
        }
    },
    "timeout": {
        "xmppconnectionError": "20s"
    }
    }
    {{ end }}
    EOH
      destination = "/vault/secrets/settings.json"
      exec {
        command = ["true"]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: fpush
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        sidecar.istio.io/inject: "true"
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "fpush"
        vault.security.banzaicloud.io/vault-skip-verify: "false"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-agent: "true"
        vault.security.banzaicloud.io/vault-agent-init: "true"
        vault.security.banzaicloud.io/vault-agent-configmap: "fpush-config-apns-vault-agent"
        vault.security.banzaicloud.io/vault-agent-once: "true"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: default
      containers:
      - name: busybox
        image: busybox
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65532
          runAsGroup: 1000
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop: [ALL]
        args: ["/bin/sh", "-c", "sleep 120"]
        env:
          - name: PUSH_ENVIRONMENT
            value: "${vault:secret/data/applications/production/fpush_apns#environment}"
```
