### ISSUE TITLE
Vault ServiceMonitor doesn't use jobLabel field correctly

### ISSUE THREAD

**Issue by maresac** [bank-vaults/vault-operator#366]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.19.0

### Installation Type

Official Helm chart

### Kubernetes Version

1.24.9

### Kubernetes Distribution/Provisioner

VMWare/Tanzu

### Expected Behavior

The ServiceMonitor deployed by the operator should configure the `jobLabel` field properly, such that all Vault endpoints belonging to a single Vault cluster are scraped with the same job name. 

The job name for all Vault endpoints belonging the same cluster should be set to the name of the Vault custom resource defining the cluster.

### Actual Behavior

Currently the `jobLabel` in the ServiceMonitor definition is set to the name of the Vault custom resource (see https://github.com/bank-vaults/vault-operator/blob/main/pkg/controller/vault/vault_controller.go#L655). 

According to the prometheus-operator docs however, `jobLabel` should be set to the name of the label on the target Service that should be used as the job name:

> jobLabel selects the label from the associated Kubernetes Service object which will be used as the job label for all metrics.
> 
> For example if jobLabel is set to foo and the Kubernetes Service object is labeled with foo: bar, then Prometheus adds the job="bar" label to all ingested metrics.
> 
> If the value of this field is empty or if the label doesn’t exist for the given Service, the job label of the metrics defaults to the name of the associated Kubernetes Service.

(source: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitor) 

Setting `jobLabel` to the Vault custom resource name leads to the prometheus-operator falling back to using the Service name, which is different for each Vault node. Therefore each Vault node will be scraped with an individual job name.

### Steps To Reproduce

1. Deploy 3-node Vault instance with ServiceMonitor enabled. 
2. Look at job names on Prometheus scrape targets:
![vault-prometheus](https://github.com/bank-vaults/vault-operator/assets/16348965/53506ed4-240d-4b76-a570-04fbf1feb75d)

### Configuration

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: test
spec:
  size: 3
  serviceMonitorEnabled: true
  config:
    storage:
      raft:
        path: /vault/file
    listener:
      tcp:
        address: 0.0.0.0:8200
        telemetry:
          unauthenticated_metrics_access: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      prometheus_retention_time: 12h
      disable_hostname: true
[...]
```

### Additional Information

I think this can easily be fixed by setting the `jobLabel` to `"vault_cr"` in the [vault controller](https://github.com/bank-vaults/vault-operator/blob/main/pkg/controller/vault/vault_controller.go#L655). I can create a PR with the fix.
