### ISSUE TITLE
Make POD_NAMESPACE available as a standard environment variable

### ISSUE THREAD

**Issue by larsks** [bank-vaults/vault-operator#378]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

In addition to `POD_NAME`, which is already included in the pod specs generated by the operator, you should also include `POD_NAMESPACE`. This would for example allow replacing this, which requires manual editing when deployed anywhere other than the `default` namespace:

```
  config:
    [...]
    api_addr: https://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
```

With:

```
  config:
    [...]
    api_addr: https://vault.${.Env.POD_NAMESPACE}:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
```

This would potentially simplify [these instructions](https://bank-vaults.dev/docs/tips-and-tricks/custom-namespace/).

### Proposed Solution

Include `POD_NAMESPACE` in generated pod specs:

```
      Env: withSidecarEnv(v, withTLSEnv(v, true, withCredentialsEnv(v, withCommonEnv(v, []corev1.EnvVar{
        {
          Name: "POD_NAMESPACE",
          ValueFrom: &corev1.EnvVarSource{
            FieldRef: &corev1.ObjectFieldSelector{
              FieldPath: "metadata.namespace",
            },
          },
        },
        {
          Name: "POD_NAME",
          ValueFrom: &corev1.EnvVarSource{
            FieldRef: &corev1.ObjectFieldSelector{
              FieldPath: "metadata.name",
            },
          },
        },
      })))),
```
