### ISSUE TITLE
Configurer is not deployed

### ISSUE THREAD

**Issue by saksmt** [bank-vaults/vault-operator#462]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.22.1

### Installation Type

Official Helm chart

### Kubernetes Version

1.27.3

### Kubernetes Distribution/Provisioner

kind

### Expected Behavior

Vault configurer is up and running, accepting `vault_cr` labeled config maps and kv v2 at `platform/secrets` is eventually created.

### Actual Behavior

No vault configurer is deployed, nothing listens for config maps and no errors or warnings are reported anywhere.

### Steps To Reproduce

1. Start any cluster
2. Deploy operator (SA is customized to `vault-root`), namespace - `security-vault`
3. `kubectl apply` provided yaml (note missing `externalConfig` field!)

### Configuration

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-storage
  namespace: security-vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 10Gi
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: security-vault
spec:
  caNamespaces:
    - "*"
  config:
    api_addr: https://vault.security-vault:8200
    cluster_addr: https://${.Env.POD_NAME}:8201
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_disable: true
    log_format: json
    storage:
      raft:
        path: /vault-storage
    ui: true
  serviceAccount: vault-root
  serviceRegistrationEnabled: true
  serviceType: ClusterIP
  size: 1
  unsealConfig:
    kubernetes:
      secretNamespace: security-vault
    options:
      secretShares: 5
      secretThreshold: 4
  vaultInitContainers:
    - command:
        - /bin/sh
        - -c
        - chown -R 100:1000 /vault/file
      image: busybox
      imagePullPolicy: IfNotPresent
      name: raft-permission
      volumeMounts:
        - mountPath: /vault/file
          name: vault-storage
  volumeMounts:
    - mountPath: /vault-storage
      name: vault-storage
  volumes:
    - name: vault-storage
      persistentVolumeClaim:
        claimName: vault-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: vault-configurator
    vault_cr: vault
  name: platform-kv-secrets
  namespace: security-vault
data:
  vault-config.yml: |
    secrets:
      - type: kv
        options:
          version: "2"
        path: platform/secrets
```

### Logs

```shell
None. And that is an issue in itself.
```

### Additional Information

This [check](https://github.com/bank-vaults/vault-operator/blob/e312bf45cfabc7f19bc195fc45d6e598e86ec709/pkg/controller/vault/vault_controller.go#L484) is frustratingly difficult to figure out and debug. It is poorly documented and is very questionable why such behavior even exists. 

Motivation: by default one would expect that not providing any `externalConfig` in vault CR would leave one with working vault instance that can be further customized in a decoupled way via config maps. But that assumption is incorrect and it is not documented (whole `vault_cr` stuff is really can be figured out through digging through examples, but that is another issue entirely) anywhere.
