### ISSUE TITLE
Helm template error when deploying using ArgoCD

### ISSUE THREAD

**Issue by virtyaluk** [bank-vaults/vault-operator#526]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Operator Version

1.22.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.29.0

### Kubernetes Distribution/Provisioner

kind

### Expected Behavior

ArgoCD to deploy vault-operator successfully.

### Actual Behavior

ArgoCD deployment fails at the helm template step due to an undefined `common.capabilities.policy.apiVersion` variable in `pdb.yaml` file.

ArgoCD Application manifest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m

  source:
    repoURL: https://github.com/bank-vaults/vault-operator.git
    path: deploy/charts/vault-operator
    targetRevision: HEAD
    helm:
      valuesObject:
        replicaCount: 2
        resources: {}
        monitoring:
          serviceMonitor:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "vault"

```

### Logs

```shell
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template vault-operator-helm --namespace vault --kube-version 1.29 --values /tmp/95925ec4-62df-4a95-bc23-16fdab99d17d <api versions removed> --include-crds` failed exit status 1: Error: template: vault-operator/templates/pdb.yaml:2:15: executing "vault-operator/templates/pdb.yaml" at <include "common.capabilities.policy.apiVersion" .>: error calling include: template: no template "common.capabilities.policy.apiVersion" associated with template "gotpl" Use --debug flag to render out invalid YAML
```
