### ISSUE TITLE
Set kv secret engine ttl time

### ISSUE THREAD

**Issue by srekkas** [bank-vaults/vault-operator#595]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Problem Description

I need to set "Default Lease TTL" on kv secret engine

### Proposed Solution

add option like this:

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 1
          default_ttl: 1h

**Comment by HenriBlacksmith** [comment]
Would it make sense to use the config key to add the mount TTL configurations to reproduce Vault API structure?: https://developer.hashicorp.com/vault/api-docs/system/mounts#config

```yaml
secrets:
  - path: secret
    type: kv
    description: General secrets.
    options:
      version: 1
    config:
      default_lease_ttl: 1h
      max_lease_ttl: 1d
```
