### ISSUE TITLE
Add `app.kubernetes.io/instance` to selector.matchLabels

### ISSUE THREAD

**Issue by komasztania** [bank-vaults/vault-operator#612]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Problem Description

Could you add `app.kubernetes.io/instance` to selector.matchLabels ?

### Proposed Solution

```
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
```

### Additional Information

reference: https://github.com/bank-vaults/vault-secrets-webhook/blob/295df329b7be7f6028f992501fc6629e421944c9/deploy/charts/vault-secrets-webhook/templates/webhook-deployment.yaml#L20
