### ISSUE TITLE
Override some fields of the Bank-Vaults container in the vault-configurer deployment

### ISSUE THREAD

**Issue by csatib02** [bank-vaults/vault-operator#631]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Problem Description

 Currently, the operator does not allow merging of the 'containers' array into the predefined PodSpec.

### Proposed Solution

See: https://github.com/bank-vaults/vault-operator/pull/512

**Comment by csatib02** [comment]
Well I've done a release yesterday, but sure :)

**Comment by csatib02** [comment]
The release is ready: [v1.23.2](https://github.com/bank-vaults/vault-operator/releases/tag/v1.23.2)

**Comment by dhumphries-sainsburys** [comment]
@csatib02 - Almost 

It does something weird with some of the env vars as it seems to lose what i assume are internal ones

```
        - name: VAULT_ADDR
          value: https://vault.vault:8200
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        - name: NAMESPACE
          value: vault
```

Before:
```
        - name: VAULT_ADDR
          value: https://vault.vault:8200
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        - name: NAMESPACE
          value: vault
        - name: AZURE_TENANT_ID
          value: <uuid>
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/wi/token/azure-identity-token
        - name: AZURE_AUTHORITY_HOST
          value: https://login.microsoftonline.com/
        - name: NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME
          value: lab-ne-core
        - name: NEW_RELIC_METADATA_KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NEW_RELIC_METADATA_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME
          value: bank-vaults
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME
          value: ghcr.io/bank-vaults/bank-vaults:v1.32.1
        - name: NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME
          value: vault-configurer
```
After:
```
        - name: AZURE_CLIENT_ID
          value: <uuid>
        - name: AZURE_TENANT_ID
          value:<uuid>
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/wi/token/azure-identity-token
        - name: AZURE_AUTHORITY_HOST
          value: https://login.microsoftonline.com/
        - name: NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME
          value: lab-ne-core
        - name: NEW_RELIC_METADATA_KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NEW_RELIC_METADATA_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME
          value: bank-vaults
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME
          value: ghcr.io/bank-vaults/bank-vaults:v1.32.1
        - name: NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME
          value: vault-configurer
```

Of course i could just provide these ones just not sure what is expected to work vs not
