### ISSUE TITLE
Change provision order in Vault configurer

### ISSUE THREAD

**Issue by paraddise** [bank-vaults/vault-operator#734]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [x] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Operator Version

1.22.3

### Installation Type

Official Helm chart

### Kubernetes Version

1.32.0

### Kubernetes Distribution/Provisioner

Bare Metal

### Expected Behavior

I specified auth with mount path `oidc`, then specified `group-alias` for this mount path.
Confugurer creates auth first of all, and then creates group-alias

### Actual Behavior

I specified auth with mount path `oidc`, then specified `group-alias` for this mount path.
When `configurer` tries to configure vault it fails with error that mountpath doesn't exist and doesn't continue to provision this mountpath

### Configuration

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 2
  externalConfig:
    groups:
      - name: admin
        policies:
          - admin
        metadata: {}
        type: external
    group-aliases:
      - name: admin
        group: admin
        mountpath: oidc
    auth:
      - type: oidc
        path: oidc
        config:
          oidc_discovery_url: "https://keycloak.example.com/realms/master"
          oidc_client_id: "${env `KEYCLOAK_CLIENT_ID`}"
          oidc_client_secret: "${env `KEYCLOAK_CLIENT_SECRET`}"
          default_role: "default"
        roles:
          - name: default
            user_claim: email
            groups_claim: "/resource_access/vault/roles"
            bound_audiences:
              - vault
            allowed_redirect_uris:
              - https://vault.example.com/ui/vault/auth/oidc/oidc/callback
              - https://vault.example.com/oidc/oidc/callback
```

### Logs

```shell
2025/02/25 10:40:33 INFO applying config file: /config/vault-configurer/vault-config.yml
2025/02/25 10:40:33 INFO checking if vault is sealed...
2025/02/25 10:40:33 INFO vault is unsealed, configuring...
2025/02/25 10:40:33 INFO audit device is already mounted file/
2025/02/25 10:40:33 INFO tuning already existing group: admin
2025/02/25 10:40:33 ERROR error configuring vault: error writing groups configurations for vault: error while adding groups aliases: error getting mount accessor for oidc: auth mount path oidc/ does not exist in vault
2025/02/25 10:40:33 INFO Failed applying configuration file: /config/vault-configurer/vault-config.yml , sleeping for 1m0s before trying again
```
