### ISSUE TITLE
Vault Operator example is not work

### ISSUE THREAD

**Issue by OlafRadicke** [bank-vaults/vault-operator#773]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [x] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Operator Version

v1.22.5

### Installation Type

Official Helm chart

### Kubernetes Version

v1.32.3+k3s1

### Kubernetes Distribution/Provisioner

K3s

### Expected Behavior

I just wanted to try out the Basic example and run a Vault instance on the Kubernet.

https://github.com/bank-vaults/vault-operator/blob/v1.22.5/examples/README.md

### Actual Behavior

Nothing happens. The logs can be found in the operator's pod:

```json
{"level":"info","ts":"2025-04-24T09:26:45Z","msg":"Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes requeuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler","controller":"vault-controller","object":{"name":"vault","namespace":"default"},"namespace":"default","name":"vault","reconcileID":"06c53ae0-8ebd-47f9-8f14-7852fd074857"}
{"level":"error","ts":"2025-04-24T09:26:45Z","msg":"Reconciler error","controller":"vault-controller","object":{"name":"vault","namespace":"default"},"namespace":"default","name":"vault","reconcileID":"06c53ae0-8ebd-47f9-8f14-7852fd074857","error":"vaults.vault.banzaicloud.com \"vault\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```

### Steps To Reproduce

Install Vault operator over ArgoCD:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-operator
    server: https://kubernetes.default.svc
  project: vault-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: deploy/charts/vault-operator
    repoURL: https://github.com/bank-vaults/vault-operator.git
    targetRevision: v1.22.5
```
Clone git repo and change branch to tag v1.22.5 and fire up kustomize...

```bash
$ git checkout v1.22.5
$ EXAMPLE=base
$ kustomize build github.com/bank-vaults/vault-operator/examples/$EXAMPLE  | kubectl apply -f -
```

### Configuration

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault
subjects:
- kind: ServiceAccount
  name: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default
---
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  config:
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_disable: true
    log_level: debug
    storage:
      inmem: {}
    ui: true
  externalConfig:
    auth:
    - roles:
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - default
        name: default
        policies:
        - allow_secrets
        ttl: 1h
      type: kubernetes
    policies:
    - name: allow_secrets
      rules: |
        path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        }
    secrets:
    - description: General secrets.
      options:
        version: 2
      path: secret
      type: kv
  image: hashicorp/vault:1.14.8
  serviceAccount: vault
  size: 1
```

### Logs

```shell
{"level":"info","ts":"2025-04-24T09:26:45Z","msg":"Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes requeuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler","controller":"vault-controller","object":{"name":"vault","namespace":"default"},"namespace":"default","name":"vault","reconcileID":"06c53ae0-8ebd-47f9-8f14-7852fd074857"}
{"level":"error","ts":"2025-04-24T09:26:45Z","msg":"Reconciler error","controller":"vault-controller","object":{"name":"vault","namespace":"default"},"namespace":"default","name":"vault","reconcileID":"06c53ae0-8ebd-47f9-8f14-7852fd074857","error":"vaults.vault.banzaicloud.com \"vault\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```
