### ISSUE TITLE
No option in Vault CRD for adding volumes to vault-configurer pod?

### ISSUE THREAD

**Issue by larsks** [bank-vaults/vault-operator#815]
I need to mount a ConfigMap in the `vault-configurer-...` pod so that I can reference values in `${ file `...` }` directives. While there are configuration options in the Vault CRD that allow one to add mounts to the vault pod itself, there doesn't appear to be any way to perform the same operation for the configurer pod.

I saw that there is a `vaultConfigurerPodSpec`, so I tried this:

```
spec:
  vaultConfigurerPodSpec:
    volumes:
    - name: my-ca-certs
      configMap:
        name: my-ca-certs
    containers:
    - name: bank-vaults
      volumeMounts:
      - name: my-ca-certs
        mountPath: /cacerts
```

But that didn't appear to have any effect. Event after deleting the `vault-configurer` deployment and waiting for the operator to re-create it, the new deployment does not include the above content.

I'm currently using the Helm chart version 1.22.6.
