### ISSUE TITLE
Vault-Configurer configures only the first authentication in the auth list of spec.externalConfig from CRD

### ISSUE THREAD

**Issue by rpcyber** [bank-vaults/vault-operator#816]
Bank-Vaults Image Tag
v1.31.3

Installation Type
Official Helm chart

Vault version:
v1.19.3

Kubernetes Version
v1.32.3-eks-4096722

Kubernetes Distribution/Provisioner
K8S/EKS

My externalConfig block in the bank vaults CRD

```
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: blabla
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      # Authentication for Shared cluster, where Vault is running
      - type: kubernetes
        path: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
        roles:
          - name: vault
            bound_service_account_names:
              - vault-operator
            bound_service_account_namespaces:
              - vault
            policies:
              - allow_secrets
            ttl: 1h
      # Authnetication for DEV Cluster
      - type: jwt
        path: dev
        config:
          oidc_discovery_url: https://oidc.eks.eu-west-1.amazonaws.com/id/<REDACTED> 
        roles:
          - name: kiali
            user_claim: sub
            bound_subject: system:serviceaccount:kiali-operator:kiali-operator
            bound_audiences:
              - https://kubernetes.default.svc
            policies:
              - blabla
            ttl: 1h
      # OIDC authentication via dex and Azure AD federation
      - type: oidc
        path: oidc
        description: "OIDC auth via Dex"
        config:
          oidc_discovery_url: "https://dex.my.company"
          oidc_client_id: "${ env `CLIENT_ID` }"
          oidc_client_secret: "${ env `CLIENT_SECRET` }"
          default_role: "oidc"
        roles:
          - name: oidc
            role_type: oidc
            bound_audiences: "${ env `CLIENT_ID` }"
            oidc_scopes:
              - "email"
            allowed_redirect_uris:
              - "https://vault.my.company/oauth2/callback"
              - "https://vault.my.company/ui/vault/auth/oidc/oidc/callback"
              - "https://vault.my.company/oidc/callback"
            user_claim: "email"
            #bound_claims:
            #  groups: ["My_Group"]
            policies:
              - "allow_secrets"
            verbose_oidc_logging: true
```

Expected Behavior
All these 3 authentications are enabled for vault

Actual behavior
Only the first one in the list is enabled

```
vault auth list
Path           Type          Accessor                    Description                Version
----           ----          --------                    -----------                -------
kubernetes/    kubernetes    auth_kubernetes_c6472d90    kubernetes backend         n/a
token/         token         auth_token_b0718f43         token based credentials    n/a
```
Vault-Configurer logs
```
2025/06/19 13:18:07 INFO vault metrics exporter enabled: :9091/metrics
2025/06/19 13:18:07 INFO applying config file: /config/vault-configurer/vault-config.yml
2025/06/19 13:18:07 INFO checking if vault is sealed...
2025/06/19 13:18:07 INFO watching directory for changes: /config/vault-configurer/
2025/06/19 13:18:08 INFO vault is unsealed, configuring...
2025/06/19 13:18:08 INFO adding auth method kubernetes (kubernetes)
2025/06/19 13:18:08 INFO adding policy allow_secrets
2025/06/19 13:18:08 INFO adding policy blabla
2025/06/19 13:18:08 INFO tuning already existing secret engine secret/
2025/06/19 13:18:08 INFO successfully configured vault
```

I wasn't able to find out how to increase its verbosity. I've seen that startup command for this pod is bank-vaults configure <ARGUMENTS>.  I've executed manually the command inside pod adding --disable-metrics as exporter port 9091 was used and I'm seeing same output.

Did bank-vaults configure --help and I've seen no verbosity flag.
