### ISSUE TITLE
Incorrect ServiceMonitor.spec.endpoints when docker registry proxy with custom port used to pull vault image

### ISSUE THREAD

**Issue by trombonax** [bank-vaults/vault-operator#95]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.

### Operator Version

1.19.0

### Installation Type

Official Helm chart

### Kubernetes Version

v1.25.7

### Kubernetes Distribution/Provisioner

VMware Tanzu

### Expected Behavior

With used docker registry proxy with custom port to pull vault image, e.g. 
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
spec:
...
  image: docker.proxy.local:5008/hashicorp/vault:1.14.0
```

I'am expect modern version ServiceMonitor.spec.endpoints:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 30s
    params:
      format:
      - prometheus
    path: /v1/sys/metrics
    port: api-port
    scheme: https
    tlsConfig:
      ca: {}
      cert: {}
      insecureSkipVerify: true
```

 

### Actual Behavior

In pkg/apis/vault/v1alpha1/vault_types.go function `func (spec *VaultSpec) GetVersion() (*semver.Version, error)` use `strings.Split(spec.Image, ":")`  to obtain vault version:
```
// GetVersion returns the version of Vault
func (spec *VaultSpec) GetVersion() (*semver.Version, error) {
    version := strings.Split(spec.Image, ":") <---------------------------------------------------
    if len(version) != 2 {
        return nil, errors.New("failed to find Vault version")
    }
    return semver.NewVersion(version[1])
}
```
But when used docker registry proxy with custom port to pull vault image, e.g. `docker.proxy.local:5008/hashicorp/vault:1.14.0` this function return incorrect vault version for function 
`func serviceMonitorForVault(v *vaultv1alpha1.Vault) *monitorv1.ServiceMonitor` in pkg/controller/vault/vault_controller.go:
```
vaultVersionWithPrometheus := semver.MustParse("1.1.0")
version, err := v.Spec.GetVersion()
if err == nil && !version.LessThan(vaultVersionWithPrometheus) {
```

As result vault-operator produces old version ServiceMonitor.spec.endpoints:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 30s
    port: prometheus
```

 

### Steps To Reproduce

1. Deploy banzaicloud-stable/vault-operator 1.19.0
2. Create custom resource vault with values:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
spec:
...
  image: docker.proxy.local:5008/hashicorp/vault:1.14.0
  statsdDisabled: true
  serviceMonitorEnabled: true
  serviceRegistrationEnabled: true
  config:
    listener:
      tcp:
...
        telemetry:
          unauthenticated_metrics_access: true
...
    telemetry:
      disable_hostname: true
      prometheus_retention_time: 24h
```
3. Get vault ServiceMonitor endpoints
```
kubectl -n vault get ServiceMonitor vault -o jsonpath-as-json={.spec.endpoints}
```
